apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadmauo6142-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadmauo6142-tenant-component
    app.kubernetes.io/part-of: loadmauo6142-tenant-app
  name: loadmauo6142-tenant-component
  namespace: loadmauo6142-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadmauo6142-tenant-component
    weight: null
status: {}
